version: '3'

services:
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./etc/letsencrypt/live:/etc/letsencrypt/live:rw
    network_mode: host
      
