version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./etc/letsencrypt/live:/etc/letsencrypt/live:rw
    network_mode: host
      
