version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 69542068ef65466a1c
      POSTGRES_USER: carbonapi
      POSTGRES_DB: carbonapi
    ports: 
     - 5431:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "carbonapi"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  web: 
     build: .
     command: ["./autostart.sh"]
     restart: always
     ports: 
      - 3001:3000
     depends_on:
        - db
    
volumes:
  db-data:
